version: '3'

services:
  db:
    image: postgres
    environment:
        POSTGRES_DB: db
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
  web:
    build: .
    command: >
      sh -c "chmod +x wait-for-postgres.sh &&
             ./wait-for-postgres.sh db:5432 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
